/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { JavierProjContrato } from "./JavierProjContrato";
export * as factories from "./factories";
export { JavierProjContrato__factory } from "./factories/JavierProjContrato__factory";
