/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface JavierProjContratoInterface extends Interface {
  getFunction(
    nameOrSignature: "actualizarMensaje" | "obtenerMensaje"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "actualizarMensaje",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerMensaje",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "actualizarMensaje",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerMensaje",
    data: BytesLike
  ): Result;
}

export interface JavierProjContrato extends BaseContract {
  connect(runner?: ContractRunner | null): JavierProjContrato;
  waitForDeployment(): Promise<this>;

  interface: JavierProjContratoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actualizarMensaje: TypedContractMethod<
    [_nuevoMensaje: string],
    [void],
    "nonpayable"
  >;

  obtenerMensaje: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actualizarMensaje"
  ): TypedContractMethod<[_nuevoMensaje: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "obtenerMensaje"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
